name: tuan08
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.1.0
  cached_network_image: ^3.2.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  provider: ^6.0.0
  path: ^1.9.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

